#include "klib.h"

// Declare all test case functions.
// testcases.h generated by Makefile from all test_*.c files.
#include "testcases.h"

typedef struct TestCaseRef_struct {
	TestCase_fn test_case;
	const char *test_name;
} TestCaseRef;

// NULL-terminated array of function pointers to all test cases
// testcases.inc is generated by Makefile from all test_*.c files.
TestCaseRef all_test_cases[] = {
#include "testcases.inc"
	{ NULL, "" }
};

int main(int argc, char *argv[])
{
	UNUSED(argc);
	UNUSED(argv);

	printf("Testing\n");
	TestCounter test_counter = {0};

	int i;
	for (i = 0; all_test_cases[i].test_case; ++i) {
		test_counter.test_name = all_test_cases[i].test_name;
		all_test_cases[i].test_case(&test_counter);
	}

	if (test_counter.failure_count)
		printf("Failed!  ");
	else
		printf("Success! ");

	printf("[cases: %d, tests: %d, failures: %d]\n", i, test_counter.test_count, test_counter.failure_count);

    return test_counter.failure_count;
}

