#include "klib.h"

// Declare all test case functions.
// all_tests.h generated by Makefile from all test_*.c files.
#include "testcases.h"

// NULL-terminated array of function pointers to all test cases
// all_tests.inc is generated by Makefile from all test_*.c files.
TestCase_fn all_test_cases[] = {
#include "testcases.inc"
	NULL
};

int main(int argc, char *argv[])
{
	UNUSED(argc);
	UNUSED(argv);

	printf("Testing\n");
	TestCounter test_counter = {0};

	for (int i = 0; all_test_cases[i]; ++i)
		all_test_cases[i](&test_counter);

	if (test_counter.failure_count)
		printf("Failed!  [tests: %d, failures: %d]\n", test_counter.test_count, test_counter.failure_count);
	else
		printf("Success!  [tests: %d, failures: 0]\n", test_counter.test_count);

    return test_counter.failure_count;
}

