#include "test.h"

// Declare all test case functions.
// testcases.h is generated by discover_tests.awk.
#include "testcases.h"

// NULL-terminated table of function pointers to all test cases.
// testcases.inc is generated by discover_tests.awk.
struct 
{
	void (*test_case)(void);
	const char *test_name;
}
all_test_cases[] = {
#include "testcases.inc"
	{ NULL, "" }
};

struct
{
	int test_count, failure_count;
	const char *test_name;
}
test_stats = {0};

void test_assert(bool condition, struct SourceLocation source, const char *msg)
{
	++test_stats.test_count;
	if (!condition)
	{
		debug_print(stderr, source, "Test %s FAILED: %s", test_stats.test_name, msg);
		++test_stats.failure_count;
	}
}

int main(int argc, char *argv[])
{
	UNUSED(argc);
	UNUSED(argv);

	printf("Testing\n");

	int i;
	for (i = 0; all_test_cases[i].test_case; ++i) 
	{
		test_stats.test_name = all_test_cases[i].test_name;
		all_test_cases[i].test_case();
	}

	printf("%s [cases: %d, tests: %d, failures: %d]\n",
	       test_stats.failure_count ? "Failed!  " : "Success! ", 
	       i, test_stats.test_count, test_stats.failure_count);

	return test_stats.failure_count;
}

